/*
SQLyog Ultimate v12.4.3 (64 bit)
MySQL - 10.4.21-MariaDB : Database - ml
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`ml` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `ml`;

/*Table structure for table `naivebayes_textclassifier` */

DROP TABLE IF EXISTS `naivebayes_textclassifier`;

CREATE TABLE `naivebayes_textclassifier` (
  `dataset_id` int(11) NOT NULL AUTO_INCREMENT,
  `response` text DEFAULT NULL,
  `label` varchar(30) NOT NULL,
  PRIMARY KEY (`dataset_id`)
) ENGINE=InnoDB AUTO_INCREMENT=501 DEFAULT CHARSET=utf8mb4;

/*Data for the table `naivebayes_textclassifier` */

insert  into `naivebayes_textclassifier`(`dataset_id`,`response`,`label`) values 
(1,'beli motor pertalite pakai pertamina saya buat mobil berisik pluto','Netral'),
(2,'PT Pertamina Persero resmi jual mekanisme beli solar pertalite lewat website mypertamina, baca berita beli pertalite solar harus pakai topik promosi pertalite saya','Netral'),
(3,'Hebat, tenang, beli Pertalite & Solar pakai aplikasi Mypertamina mobile, check it out','Positif'),
(4,'Tenang, beli Pertalite & Solar pakai aplikasi MyPertamina, yuk simak','Positif'),
(5,'Guys, tenang kalo beli Pertalite & Solar pake aplikasi hp MyPertamina, lol','Positif'),
(6,'Tenang, beli PertaliteSolar pakai aplikasi MyPertamina gaes','Positif'),
(7,'guys tenang beli pertalite & solar pake hp mypertamina lihat','Positif'),
(8,'Jangan risau guys beli Pertalite & Solar pake aplikasi MyPertamina lihat','Netral'),
(9,'fyi bestie tenang beli pertalite & solar pakai aplikasi mypertamina mobile lihat','Positif'),
(10,'Tenang guys, beli Pertalite & Solar pakai hp mypertamina, check it out, thumbs up light skin tone','Positif'),
(11,'Guys, beli Pertalite & Solar pake Myp aplikasi mobile ertamina, daftar untuk menerima','Netral'),
(12,'subsidi.   wah guys tenang beli pertalite & solar pakai hp mypertamina lihat','Positif'),
(13,'tenang beli Pertalite & Solar pake aplikasi MyPertamina gaes gaes gaes','Positif'),
(14,'kalo beli Pertalite & Solar pake hp MyPertamina, Hebat lah pokoknya','Positif'),
(15,'tenang beli Pertalite & Solar menggunakan aplikasi Mypertamina, lihat','Positif'),
(16,'Tenang, beli Pertalite & Solar menggunakan aplikasi MyPertamina, mari lihat','Positif'),
(17,'Tenang jika membeli Pertalite & Solar menggunakan aplikasi MyPertamina, lihat guys','Positif'),
(18,'bingung, tenang, beli saja pertalite & solar menggunakan mypertamina','Negatif'),
(19,'aplikasi seluler.   Guys tenang aja beli Pertalite & Solar pake hp MyPertamina tau kan','Positif'),
(20,'Tenang guys, beli solar pertalite pake aplikasi mypertamina gampang kok, gak ribet, yuk simak','Positif'),
(21,'Tenang, beli Pertalite & Solar pake aplikasi MyPertamina yuk simak','Positif'),
(22,'Hebat lah pokoknya beli Pertalite & Solar pakai aplikasi Mypertamina simak','Positif'),
(23,'Guys tenang aja kalo beli Pertalite & Solar pake hp MyPertamina','Positif'),
(24,'Tenang beli Pertalite & Solar pake aplikasi MyPertamina gaes','Positif'),
(25,'guys tenang aja beli pertalite & solar pakai aplikasi mypertamina mobile lihat','Positif'),
(26,'Tenang sob, beli Pertalite & Solar pakai aplikasi MyPertamina, sampai jumpa','Positif'),
(27,'tenang, beli pertalite & solar pakai hp aplikasi mypertamina guys, check it out','Positif'),
(28,'tau gak, saya beli Pertalite diesel pakai Mypertamina','Netral'),
(29,'aplikasi seluler.   fyi guys, beli pertalite & solar pakai hp aplikasi mypertamina, lihat','Netral'),
(30,'fyi guys, beli pertalite & solar pakai hp aplikasi mypertamina, lihat','Netral'),
(31,'tau gak, saya beli Pertalite Solar pake','Netral'),
(32,'aplikasi hp mypertamina.   Tenang, beli Pertalite & Solar pakai aplikasi MyPertamina gaes, check it out','Positif'),
(33,'Tenang sob, beli Pertalite & Solar pakai aplikasi MyPertamina, sampai jumpa','Positif'),
(34,'Tenang, beli Pertalite & Solar pakai aplikasi MyPertamina, yuk lihat Hebatnya','Positif'),
(35,', tenang aja, beli Pertalite & Solar pakai aplikasi Mypertamina simak','Positif'),
(36,'Guys, tenang aja kalau beli Pertalite & Solar pakai hp MyPertamina','Positif'),
(37,'Guys, beli Pertalite & Solar pake aplikasi Mypertamina, daftar untuk dapat subsidi','Netral'),
(38,'Jangan khawatir, beli Pertalite & Solar menggunakan aplikasi MyPertamina, lihat','Netral'),
(39,'fyi bestie tenang beli pertalite & solar menggunakan aplikasi mypertamina mobile lihat','Positif'),
(40,'Tenang guys, beli Pertalite & Solar menggunakan ponsel mypertamina, mari kita lihat, acungan jempol warna kulit cerah','Positif'),
(41,'Guys, beli Pertalite & Solar menggunakan aplikasi mobile Mypertamina, mendaftar untuk menerima subsidi','Netral'),
(42,'mendaftar untuk membeli bensin pertalite menggunakan','Netral'),
(43,'aplikasi mypertamina.   Pertamina Teguh Beli Pertalite Diesel Pakai Aplikasi MyPertamina Mobil, Hore','Negatif'),
(44,'PT Pertamina Persero resmi jual mekanisme beli solar pertalite lewat website mypertamina, baca berita, beli pertalite solar pasti pakai saya','Netral'),
(45,'politisi PKS topik promosi Pertamina, nilainya beli Pertalite pakai Mypertamina menambah beban masyarakat, Jokowibebanrakyat,Jokowibebanrakyat46','Netral'),
(46,'PT Pertamina Persero resmi jual mekanisme beli solar pertalite lewat website mypertamina, baca berita, beli pertalite solar harus pakai saya yang dipromosikan','Netral'),
(47,'Pertaminatopik klaim pertamina itu beli pertalite pakai mypertamina mudah dijangkau masyarakat lengkap berita cepat ekonomi uang ekonomi indonesia','Positif'),
(48,'Kuota BBM beli pertalite pakai mypertamina menyoroti zona ekonomi','Positif'),
(49,'PT Pertamina Persero resmi menjual mekanisme pembelian solar pertalite via website mypertamina , baca berita, beli pertalite diesel harus pakai Perta saya mina promotetopic','Netral'),
(50,'my pertamina akses SPBU daftar website mengemudi yang membutuhkan pertalite daftar website tercetak barcode print barcode bekas beli pertalite mudah-mudahan bright','Positif'),
(51,'PT Pertamina Persero resmi menjual mekanisme pembelian solar pertalite melalui website mypertamina, baca berita, beli pertalite solar, anda harus pakai pertalite yang saya promosikantopik','Netral'),
(52,'PT Pertamina Persero resmi jual mekanisme beli pertalite solar lewat website mypertamina, baca berita, beli pertalite solar, anda harus pakai pertalite saya promosikan','Netral'),
(53,'topik beli mobil pertalite dengan cash register mypertamina','Netral'),
(54,'beli pertalite pakai mypertamina cek jenis kendaraan daftar daerah','Netral'),
(55,'beli pertalite pakai mypertamina new juli anti ribet','Positif'),
(56,'trial beli pertalite solar pakai mypertamina jakarta pertamina','Netral'),
(57,'PT Pertamina Persero resmi jual mekanisme beli solar pertalite via website mypertamina, baca beritanya beli pertalite solar harus pakai pertami saya na dipromosikantopik','Netral'),
(58,'membeli solar pertalite menggunakan mypertamina rumit untuk mendaftar untuk','Negatif'),
(59,'ponsel.   beli pertalite pakai mypertamina keuntungan luar negeri website tenaga sektor energi indonesia tele ig fb inkmedia islam rahmat semesta','Negatif'),
(60,'pertanyaan beli pertalite solar pakai','Netral'),
(61,'aplikasi mypertamina editor.   beli SPBU pertalite pakai mypertamina qr code, bawa hp','Netral'),
(62,'PT Pertamina Persero resmi jual mekanisme beli solar pertalite lewat website mypertamina, baca berita, beli pertalite solar harus pakai pertalite saya promosi','Netral'),
(63,'topik sopyan bodoh pergi ke pasar monyet sopyan bodoh membeli minyak goreng menggunakan monyet oke sopyan bodoh pergi ke pom bensin sopyan bodoh untuk membeli pertalite menggunakan aplikasi monyet mypertamina pom bensin meledak karena sopyan bodoh bermain area ponsel di pom bensin monyet berjuang wajah bodoh dengan tangan di atas mulut','Negatif'),
(64,'pro dan kontra membeli pertalite menggunakan mypertamina ciamis bingung mendukung','Negatif'),
(65,'pro dan kontra membeli pertalite menggunakan mypertamina ciamis bingung mendukung','Negatif'),
(66,'bermain ponsel, melarang SPBU membeli pertalite menggunakan aplikasi mypertamina, menolak periode penolakan, menolak periode','Netral'),
(67,'etsolutionsonedata Erickthohirjujur ​​bersih Erick thohir adalah dasar untuk membeli pertpertamina saya','Negatif'),
(68,'pakai mypertamina qr code untuk beli velg hp solar pertalite subsidi','Netral'),
(69,'.   Yang mau kasih gratisan biar motor target subsidi gak pake Pertamina saya, beli mobil cc pake Pertalite, mikirin hak motor','Netral'),
(70,'etsolutionsonedata Erickthohirjujur ​​bersih Erick thohir dimana beli pertalite pakai mypertamina','Netral'),
(71,'daftar lengkap lokasi mypertamina offline daftar indonesia beli pertalite pakai aplikasi','Positif'),
(72,'.   Erick Thohir membeli Pertalite menggunakan aplikasi Mypertamina, menerapkan sistem logistik pengukuran kebocoran, etsolution, satu data, Erickthohir, jujur ​​dan bersih','Positif'),
(73,'Erick Thohir membeli Pertalite menggunakan mypertamina etsolutions. Satu data, Erickthohir jujur,','Positif'),
(74,'lega beli pertalite diesel, Anda harus menggunakan aplikasi mypertamina, syarat download aplikasi akses berita mudah android','Positif'),
(75,'PT Pertamina Persero resmi menjual mekanisme beli solar pertalite melalui website mypertamina, baca berita, beli pertalite solar harus pakai pertalite saya','Netral'),
(76,'mohon maaf kelinci orang coba beli pertalite pake aplikasi mypertamina beli migor pake aplikasi care harga naik jokowit turun harga naik jokowit begitu juga tombol ok tombolnya anggota DPR RI BPH Minyak dan Gas berfungsi','Negatif'),
(77,'Pertamax, saya tidak pakai apk, katanya beli Pertalite diesel pakai Pertamina saya muka nyengir keringat','Netral'),
(78,'Diakui bajingan tolol yang pakai mypertamina aplikasi, velg yang beli solar pertalite, bodoh, menghasut kadrun bodoh','Negatif'),
(79,'baru posting beli BBM bersubsidi pertalite mypertamina menggunakan jeriken sudah terbit di','Positif'),
(80,'beli pertalite solar pakai mypertamina pertamina velg isi BBM bersubsidi klik baca','Positif'),
(81,'beli pertalite pakai mypertamina ribet, daftar hp, qr code, print, bayar tunai, jual mobil','Negatif'),
(82,'SPBU Jakarta jual pertalite pakai mypertamina September','Netral'),
(83,'beli pertalite pakai mypertamina dianggap repot bagi konsumen','Netral'),
(84,'trial beli pertalite pakai mypertamina pulau jawa agustus','Netral'),
(85,'Beli pertalite solar pakai mypertamina warga Pati , bikin repot','Negatif'),
(86,'Gampang bikin susah mental orang-orang di kantor sekarang, digitalisasi triliunan audit, BPK Rakyat, beli Pertalite pakai Mypertamina, Anggota DPR RI, BPH Migas, kerja, klik baca','Positif'),
(87,'PT Pertamina Persero resmi jual mekanisme beli solar pertalite via website mypertamina, baca berita, beli pertalite solar, anda harus pakai pertamina saya','Netral'),
(88,'Pertamina membuka daftar penerimaan BBM bersubsidi untuk aplikasi Mypertamina pada bulan Juli. Beli solar pertalite subsidi pakai MyPertamina Video','Netral'),
(89,'beli solar pertalite pakai','Netral'),
(90,'aplikasi mypertamina.   Video pembelian solar pertalite bersubsidi menggunakan mypertamina','Netral'),
(91,'beli bahan bakar mypertamina pertalite bersubsidi menggunakan','Netral'),
(92,'jerigen tempootomotif.   Paling laris beli pertalite pakai aplikasi mypertamina, dengan modal hp maju, beli pertalite','Positif'),
(93,'beli pertalite pakai mypertamina alasannya','Netral'),
(94,'beli pertalite pakai mypertamina alasannya','Netral'),
(95,'motor harus pakai mypertamina untuk beli pertalite jawabannya','Netral'),
(96,'Salah beli pertalite pakai mypertamina mobil jual','Netral'),
(97,'aman jarak jauh pake hp pom bensin buka aplikasi mypertamina beli','Positif'),
(98,'solar pertalite.   beli pertalite pakai mypertamina rejeki aman datanya','Positif'),
(99,'aplikasi peraturan beli pertalite pakai mypertamina jual motor di cari duit','Netral'),
(100,'betul ga beli pertalite pakai mypertamina rofik harnanto menambah kebingungan masyarakat','Positif'),
(101,'pertalite beli lpg kg pakai mypertamina indonesia berita terbaru berita pertamina','Positif'),
(102,'mypertamina register beli mobil pertalite pakai cash cnn indonesia option','Netral'),
(103,'kebijakan beli pertalite solar pakai mypertamina menuai kritik politik pks','Netral'),
(104,'beli pertalite pakai mypertamina alasan','Netral'),
(105,'tepat beli pertalite pakai mypertamina rofik harnanto menambah kebingungan','Positif'),
(106,'kebijakan masyarakat untuk membeli pertalite menggunakan mypertamina organganda','Netral'),
(107,'nilai rasional Jabar.   ','Netral'),
(108,'beli pertalite pakai mypertamina juli resiko salah arah','Netral'),
(109,'Pertamina harus pakai mypertamina beli pertalite','Netral'),
(110,'fakta mengejutkan. bukan hp mypertamina beli pertalite solar pakai email qr code','Positif'),
(111,'no hp mypertamina beli pertalite diesel pakai email qr code','Netral'),
(112,'no hp mypertamina beli pertalite solar pakai email qr code','Netral'),
(113,'PT Pertamina Persero resmi jual mekanisme beli solar pertalite via website mypertamina, baca berita , beli pertalite solar harus pakai pertalite saya','Netral'),
(114,'september beli pertalite jakarta pakai mypertamina','Netral'),
(115,'aplikasi peraturan beli pertalite pakai mypertamina, jual motor, naik mobil, mobil pribadi, angkot, uang','Netral'),
(116,'heboh beli pertalite pakai aplikasi mypertamina, dengan modal hp canggih beli pertalite','Positif'),
(117,'hiruk pikuk beli pertalite solar harus pakai mypertamina page','Netral'),
(118,'hiruk pikuk beli pertalite solar harus pakai mypertamina page all','Netral'),
(119,'Wajar kalau rezim ibu susah beli minyak goreng curahaplikasi perlindungan peduli, sulit untuk membeli pertalite di esel BBM menggunakan aplikasi Pertamina saya wajah dengan air mata sukacita wajah dengan air mata sukacita wajah dengan air mata sukacita','Positif'),
(120,'september membeli pertalite jakarta menggunakan','Netral'),
(121,'aplikasi mypertamina. heboh beli pertalite pakai aplikasi mypertamina, bermodal hp canggih, beli pertalite','Positif'),
(122,'kak, marah ente salah paham, lihat jelas beli pertalite pakai mypertamina','Negatif'),
(123,'beli pertalite solar pasti pake aplikasi pertalite saya salah ban SPBU, ban hp aktif ,bijak tolong bijakkan negeri konoha','Positif'),
(124,'Ya, saya mengerti wajah nyengir dengan keringat linkaja menang karena saya membeli pertalite menggunakan mypertamina','Netral'),
(125,'september membeli pertalite jakarta menggunakan','Netral'),
(126,'aplikasi mypertamina. hiruk pikuk beli pertalite solar harus pakai mypertamina','Netral'),
(127,'pulau jawa beli pertalite harus pakai mypertamina September','Netral'),
(128,'beli pertalite pakai mypertamina resiko selesai cepat berita ekonomi perekonomian indonesia','Positif'),
(129,'polemik beli pertalite solar lpg kg pakaimypertamina jokowi insindir','Netral'),
(130,'. menggunakan sepeda motor aplikasi Pertamina saya, membeli sandal pertalite, aman dari denda media yang terkadang menyontek jeritan berita utama','Positif'),
(131,', mengatur sopir angkot Sukabumi untuk membeli pertalite menggunakan mypertamina','Netral'),
(132,'Saya penasaran, sudah banyak netizen yang membeli solar pertalite menggunakan','Positif'),
(133,'aplikasi . beli pertalite pakai mypertamina komplain supir angkot review negatif di google play, lengkap, cepat, berita tentang ekonomi perekonomian indonesia','Negatif'),
(134,'beli pertalite pakai mypertamina new juli anti ribet link nonton film laptop malu aska vcshijab diatas normal ikat kompas talikasihhrdbacot guru bangun yumiscells ep Susahnya','Negatif'),
(135,'supir angkot beli pertalite pakai mypertamina','Negatif'),
(136,'september beli pertalite jakarta coba pakai','Netral'),
(137,'aplikasi mypertamina. PT Pertamina Persero resmi jual mekanisme beli solar pertalite lewat website mypertamina, baca berita, beli pertalite solar harus pakai pertamina saya','Netral'),
(138,'hoax beli pertalite bayar dengan mypertamina','Netral'),
(139,'Harus daftar dimana pakai mypertamina untuk beli pertalite','Netral'),
(140,'solar. tutorial pembelian pertalite solar bersubsidi menggunakan aplikasi mypertamina tvone mute','Netral'),
(141,'. Politisi PKS, nilai beli Pertalite pakai Mypertamina menambah beban masyarakat Temponasional','Netral'),
(142,'pakai ask, set beli, pakai app, beli pakai app, nanti yang pakai app beras gula bawang merah, rakyat susah bayar subsidi, tutorial kesalahan rakyat','Negatif'),
(143,'membeli pertalite solar bersubsidi menggunakan aplikasi mypertamina tvone mute tvonenews','Netral'),
(144,'membeli pertalite mypertamina nu angka SPBU melarang menggunakan','Netral'),
(145,'ponsel. tutorial beli pertalite solar bersubsidi pakai mypertamina tvone mute app tvonenews','Netral'),
(146,'ojol ciamis respon beli pertalite harus pakai mypertamina','Netral'),
(147,'Kalau daftar mypertamina bayar beli pertalite solar pakai linkaja','Netral'),
(148,'Beritabali bpsk denpasar kritik syarat beli pertalite & solar pakai aplikasi mypertamina syarat bpskdenpasar untuk pembelian BBM untuk','Netral'),
(149,'aplikasi mypertamina. trial beli pertalite pakai mypertamina ptpertamina persero pertaminapatraniaga','Netral'),
(150,'Beli Pertalite Solar Papua malu pakai mypertamina','Netral'),
(151,'Linkaja menang karena saya beli Pertalite pakai mypertamina','Netral'),
(152,'beli pertalite pakai aplikasi jual september jakarta lihat daftar','Netral'),
(153,'aplikasi mypertamina. Percobaan beli Pertalite pakai driver angkot Mypertamina objek','Netral'),
(154,'lihat beli pertalite solar pakai mypertamina','Netral'),
(155,'bpsk denpasar mengkritisi syarat beli pertalite & solar pakai','Netral'),
(156,'aplikasi mypertamina. Kalau tidak bisa konek, harus beli Pertalite, harus pakai aplikasi My Pertamina. Beli minyak goreng harus pakai','Netral'),
(157,'aplikasi proteksi perawatan Wajah Menyeringai. Jangan risau guys, beli Pertalite solar pakai cash, bukan mypertamina, ayo daftar subsidi BBM','Netral'),
(158,'mempersulit rakyat DPR beli Pertalite pakai aplikasi Mypertamina BPH Migas, cara kerjanya','Negatif'),
(159,'beli bahan bakar pertalite pakai aplikasi mypertamina dijual pada tanggal penjualan gin kota','Netral'),
(160,'saya mampu membeli mobil tetapi saya tidak mampu membeli Pertamax. Mohon maaf bagi yang menggunakan motor saya yang menggunakan NMAX. Saya tidak bisa membeli Pertamx. Kalau Pertamax, mohon maaf yang butuh Pertalite, mobilnya diisi Pertamax','Negatif'),
(161,'Anggota DPR pergi beli Pertalite pakai aplikasi Mypertamina BPH Migas kerjanya','Netral'),
(162,'beli pertalite pakai mypertamina net internet','Netral'),
(163,'regulasi, no research, SPBU, hp tidak hangus dll, dll beli pertalite solar pakai','Netral'),
(164,'aplikasi my pertamina. hadiah untuk masyarakat di bulan juli iklan beli pertalite dengan mypertamina beli minyak goreng dengan hati-hati lindungi kenaikan tarif listrik info lagi beli kg elpiji dengan hati-hati lindungi mungkin','Netral'),
(165,'lagi. karena seperti sobat Pak yang menggunakan mobil, membeli subsidi Pertalite, salah menargetkan Mypertamina, coba gunakan nomor pada daftar pilihan yang tidak memenuhi syarat untuk subsidi. Kode QR tidak cocok dengan kode QR. Kode nomor tidak cocok. Jangan beli','Negatif'),
(166,'pertalite beli pertalite solar bersubsidi menggunakan aplikasi mypertamina, penjelasannya','Netral'),
(167,'uji coba beli BBM bersubsidi menggunakan mypertamina resmi diterapkan Jakarta September pertamina bahan bakar bersubsidi mypertamina pertalite','Netral'),
(168,'beli solar pertalite bersubsidi menggunakan aplikasi mypertamina, penjelasannya','Netral'),
(169,'Yth Kadrun Bungul, Saya membeli Pertalite diesel menggunakan Mypertamina, dan saya mengendarai roda kemarahan di','Netral'),
(170,'demo seni bela diri. meme lucu beli pertalite pakai mypertamina sindir cimahi esemka','Positif'),
(171,'meme lucu beli pertalite pakai mypertamina sindir cimahi esemka','Positif'),
(172,'main di hp, larang SPBU beli pertalite pakai aplikasi mypertamina, jelas Pertamina mendiang pelawak Basuki itu mencla mencle wajah berseri-seri dengan mata tersenyum','Negatif'),
(173,'pendaftaran beli pertalite solar pakai mypertamina buka pertamina patra commerce sosialisasi pom bensin','Netral'),
(174,'meme lucu beli pertalite pakai mypertamina sindir cimahi esemka','Positif'),
(175,'lihat beli pertalite solar pakai mypertamina','Netral'),
(176,'PT Pertamina Persero resmi jual mekanisme beli solar pertalite via website mypertamina, baca beritanya beli pertalite solar harus pakai pertamina saya','Netral'),
(177,'anggota DPR pergi beli pertalite pakai aplikasi Mypertamina BPH Migas cara kerjanya','Netral'),
(178,'aturan pakai mypertamina, beli pertalite & solar bandung, simak hasil aplikasi area','Netral'),
(179,'trial beli pertalite menggunakan cairan mypertamina asn gaji artikel populer uang jumat uang','Positif'),
(180,'populer trial beli pertalite pakai mypertamina liquid asn gaji','Positif'),
(181,'aman pakai hp pom bensin, beli pertalite via','Positif'),
(182,'aplikasi mypertamina mypertamina error trial beli pertalite solar pakai','Netral'),
(183,'aplikasi. Uji coba beli pertalite pakai mypertamina, titel provinsi','Netral'),
(184,'Orang beli Pertalite pakai Mypertamina Anggota DPR RI BPH Migas kerja klik baca','Netral'),
(185,'Uji coba beli pertalite pakai mypertamina, pembulatan gelar provinsi','Netral'),
(186,'beli pertalite pakai mypertamina yana mulyana kondisi normal','Positif'),
(187,'Anggota DPRAplikasi Mypertamina BPH Migas berfungsi','Netral'),
(188,'Anggota DPR pergi membeli Pertalite menggunakan aplikasi Mypertamina BPH Migas berfungsi','Netral'),
(189,'beli pertalite harus menggunakan mypertamina daftar aplikasi mypertamina mypertamina pertalite pertalite','Netral'),
(190,'dips beli pertamax menggunakan pertamina saya jangan beli pertalite terima kasih tangan dilipat ringan skin tone','Positif'),
(191,'Anggota DPR pergi beli Pertalite pakai aplikasi Mypertamina BPH Migas berfungsi','Netral'),
(192,'resmi juli beli pertalite pakai smartphone mypertamina','Netral'),
(193,'Anggota DPR beli Pertalite pakai aplikasi mypertamina BPH Migas, semoga ke Bukadraftrkuhp Bukadraftrkuhp','Netral'),
(194,'Anggota DPR go untuk membeli Pertalite menggunakan Minyak Mypertamina BPH dan aplikasi Gas ini berfungsi','Netral'),
(195,'percobaan pembelian pertalite menggunakan','Netral'),
(196,'solusi hp mypertamina. percobaan kesalahan aplikasi mypertamina membeli pertalite diesel menggunakan','Netral'),
(197,'aplikasi. beli pertalite menggunakan aplikasi sosialisasi mypertamina, minimal pertamina gencar melakukan sosialisasi','Negatif'),
(198,'Gamudeng wajah lega bermain hp ban SPBU beli pertalite menggunakan','Netral'),
(199,'aplikasi mypertamina. beli bahan bakar pertalite solar SPBU menggunakan mypertamina','Netral'),
(200,'beli bahan bakar bersubsidi menggunakan mypertamina gaslpg mypertamina pertalite solar','Netral'),
(201,'dilarang pakai pertalite wkwkwkwk pakai aplikasi login pertamina saya beli turbo juga','Netral'),
(202,'bulan juli beli solar amp pertalite pakai','Netral'),
(203,'aplikasi mypertamina.   ','Negatif'),
(204,'beli BBM pertalite pakai aplikasi mypertamina,saluran subsidi distributif','Netral'),
(205,'september beli pertalite jakarta wajib pakai mypertamina','Netral'),
(206,'teriak sopir angkot kota bandung beli pertalite,harus pakai mypertamina,rumit','Negatif'),
(207,'PT Pertamina Persero resmi jual mekanismenya untuk beli pertalite solar lewat website mypertamina baca berita beli pertalite solar harus pakai pertamina saya klik link bio','Netral'),
(208,'Yuk simak faktanya biar ga salah paham juli beli pertalite solar pake mypertamina aplikasi, batasi beli list publik, beli BBM bersubsidi, ayo daftar BBM bersubsidi','Netral'),
(209,'jakarta beli pertalite solar harus pakai mypertamina java island september pt pertamina','Netral'),
(210,'anggota DPR beli pertalite pakai aplikasi mypertamina bph oil and gas work','Netral'),
(211,'Maaf yang berisik karena membeli Pertalite menggunakan Mypertamina, konsumen yang membawa mobil anda dengan motor tidak perlu ribet rol ling di lantai tertawa','Negatif'),
(212,'beli pertalite pakai aplikasi my pertamina lengkap dengan sistem anti bakar, bang','Positif'),
(213,'Beritajabar September Beli Pertalite Diesel di pulau jawa harus pakai MyPertamina ApiKasi MyPertamina Pulau Jawa BBM','Netral'),
(214,'beli pertalite pakai mypertamina jakarta September','Netral'),
(215,'september giliran jawa beli pertalite pakai mypertamina','Netral'),
(216,'thread september beli pertalite solar di pulau jawa harus pakai mypertamina mypertamina beli BBM bersubsidi','Netral'),
(217,'beli pertalite pakai mypertamina','Netral'),
(218,'beli solar pertalite pakai mypertamina daftar jual beli BBM bersubsidi via','Netral'),
(219,'pertalite solar beli gas lpg kg juli pakai mypertamina','Netral'),
(220,'september beli pertalite solar di pulau jawa harus pakai mypertamina','Netral'),
(221,'pendistribusian BBM bersubsidi ditargetkan beli pertalite pakai mobil mypertamina jual','Netral'),
(222,'trial beli pertalite solar pakai mypertamina bandung','Netral'),
(223,'Warga Banjarmasin yang beli pertalite wajib pakai aplikasi mypertamina, solusi tukar Pom Gambut, acungan jempol','Netral'),
(224,'Pertamina menerapkan syarat beli pertalite solar menggunakan kode qr mypertamina alasannya adalah','Netral'),
(225,'mypertamina register mobil beli pertalite dengan tunai mypertamina qrcode bahan bakar pertalite','Netral'),
(226,'pengguna velg regional lupa install aplikasi mypertamina, setel wajib pakai mypertamina, beli pertalite solar, triviatime subsidi mypertamina pertamina txtdrpengusaha','Netral'),
(227,'beli pertalite pakai mobil moto gratis mypertamina, thahjokumolo bintangemon doctor mobilbelanabi sangebanget westlife rusia toyotanewrush thorloveandthunder Strangerthing','Positif'),
(228,'Terpopuler Anies tutup outlet holywings beli Pertalite pakai aplikasi Mypertamina Sri Mulyani untuk berita Bogor Voice','Positif'),
(229,'Rules beli pertalite pakai aplikasi mypertamina keluhan nelayan di lombok, ntb, ketua dkp, lombok, nelayan, smart phone','Positif'),
(230,'juli beli BBM bersubsidi pakai aplikasi mypertamina register pertamina pertalite solar','Netral'),
(231,'beli solar pertalite pakai','Netral'),
(232,'aplikasi my pertamina. beli mobil terdaftar mypertamina pertalite dengan cash','Netral'),
(233,'beli pertalite menggunakan aplikasi mypertamina dpp betor review','Netral'),
(234,'september beli pertalite solar jakarta harus menggunakan mypertamina','Netral'),
(235,'trial beli pertalite menggunakan mypertamina official sumatera','Netral'),
(236,'mypertamina terdaftar mobil beli pertalite dengan tunai','Netral'),
(237,'Anggota dpr Brebes pergi beli pertalite menggunakan mypertamina','Netral'),
(238,'beli pertalite menggunakan mypertamina jual sepeda motor sonar wartasonora sonorabandung BBM bersubsidi mypertamina pertalite solar via','Netral'),
(239,'keyakinan bahwa pembelian pertalite menggunakan mypertamina batal','Netral'),
(240,'beli perlalite solar menggunakan aplikasi mypertamina uji coba beli pertalite solar aplikasi mypertamina Juli konsumen mau beli solar','Netral'),
(241,'aplikasi beli pertalite menggunakan mypertamina jual motor','Netral'),
(242,'beli SPBU pertalite pertamina jabodetabek pakai mypertamina','Netral'),
(243,'beli SPBU pertalite pertamina jabodetabek pakai mypertamina','Netral'),
(244,'Juli ada yang beli solar Pertalite pakai Pertamina saya','Netral'),
(245,'Pemerintah Kota Bandung naik motor pakai t he aplikasi mypertamina dan beli pertalite','Netral'),
(246,'lintasmlg juli saat mendaftar qr code beli BBM subsidi website pertamina download aplikasi pertamina saya irto ginting sekretaris perusahaan pertamina patra niaga qr code pakai beli pertalite solar adm','Netral'),
(247,'beli pertalite solar pakai aplikasi mypertamina, lihat jelas','Positif'),
(248,'transaksi SPBU . Efek bandung, beli pertalite pakai pertamina saya, beli karena cimahi','Netral'),
(249,'dilarang main SPBU, beli pertalite solar harus pakai','Netral'),
(250,'aplikasi mypertamina. Buruan buka daftar beli pertalite menggunakan link mypertamina indonesia berita terbaru pertamina mypertamina','Positif'),
(251,'news. Beli Pertalite Solar Jatim Pakai Tunai, Warga Jatim Panik Soal Isu Subsidi Batas BBM Website Bijak Mypertamina Beritabaik TimesIndonesia Informasi','Positif'),
(252,'Uji coba ketahanan beli pertalite pakai mypertamina','Netral'),
(253,'dilarang main hp saat pengisian bahan bakar SPBU, beli pertalite solar, harus pakai aplikasi my','Netral'),
(254,'pertamina . Saat saya beli Pertalite motor Samarinda pakai Mypertamina apakah saya dapat cash','Netral'),
(255,'nikmati trial beli pertalite pakai mypertamina klik baca','Positif'),
(256,'registrasi beli pertalite pakai mypertamina buka','Netral'),
(257,'beli pertalite mahal, beli minyak goreng mahal, pakai aplikasi my pertamina protection sudah , orang suruh makan enceng gondok, bagus banget','Negatif'),
(258,'pendaftaran beli pertalite pakai mypertamina open','Netral'),
(259,'trial beli pertalite pakai mypertamina','Netral'),
(260,'Pertamina bijak beli pertalite pakai Pertamina saya, batas kerjasama membangun','Positif'),
(261,'Pertamina bijak beli pertalite pakai my Pertamina batas kerjasama membangun','Positif'),
(262,'lihat cara bayar dan beli pertalite pakai mypertamina tempootomotif','Netral'),
(263,'percobaan beli pertalite pakai mypertamina','Netral'),
(264,'kebijakan beli pertalite pakai my pertamina batas kerjasama gedung','Netral'),
(265,'Warga Banjarmasin beli Pertalite wajib pakai Mypertamina warga Banjarmasin beli Batola Gambut Banjarbaru','Netral'),
(266,'pertamina bijaksana untuk membeli pertalit e menggunakan mypertamina limit kerjasama untuk membangun kerjasama untuk membangun','Positif'),
(267,'Tenang, Pertalite solar, pembelian bersubsidi dengan tunai, Surabaya, Jawa Timur, panik atas masalah batas bahan bakar, mypertamina bersubsidi mypertamina pertamina ekbis','Positif'),
(268,'Pertamina bijak membeli Pertalite menggunakan MyPertamina, batas kerjasama membangun','Positif'),
(269,'beli minyak goreng curah menggunakan aplikasi pelindung, beli pertalite menggunakan aplikasi mypertamina untuk sementara waktu, beli beras menggunakan aplikasi mysawah, beli susu menggunakan aplikasi mynenen, beli popok menggunakan aplikasi mykun, yak muka ribet dengan rolling eyes','Negatif'),
(270,'september java beli pertalite pakai mypertamina pakai','Netral'),
(271,'mypertamina lebih baik beli bensin, tunjukan struk pajak kendaraan, beli pertalite, pajak kendaraan besar, kendaraan mewah, beli pertamax','Positif'),
(272,'trial beli pertalite pakai mypertamina','Netral'),
(273,'saya beli pertalite bandung pake app daftar verifikasi gagal, nomor hp saya tidak salah daftar, sedangkan OTP SMS hp saya, tapi tidak berhasil dengan konsumsi pulsa biasa, susah bajingan','Negatif'),
(274,'Beli BBM bersubsidi pakai mypertamina, subsidi premium pertalite dicabut','Netral'),
(275,'pertamina bijak beli pertalite pakai mypertamina limit serah terima muka gantung diri gabung muka senyum sama monaco kerjasama bangun','Positif'),
(276,'registrasi beli pertalite menggunakan mypertamina adalah open','Netral'),
(277,'beli pertalite menggunakan mypertamina bukti bahwa negara mengatur kesulitan rakyat','Netral'),
(278,'aplikasi beli pertalite menggunakan mypertamina menjual','Netral'),
(279,'motor tempootomotif. Pertamina bijak beli pertalite pakai my Pertamina, batas kerjasama membangun','Positif'),
(280,'Pertamina bijak beli pertalite pakai mypertamina, batas kerjasama bangun','Positif'),
(281,'random news juli beli BBM bersubsidi harus pakai mypertamina beli biodiesel pertalite pakai linkaja','Negatif'),
(282,'pertamina bijak beli pertalite menggunakan mypertamina batas kerjasama untuk membangun','Positif'),
(283,'pertamina bijaksana untuk membeli pertalite menggunakan mypertamina kerjasama batas untuk membangun','Positif'),
(284,'Pemerintah Kota Bandung mengendarai sepeda motor menggunakan aplikasi Mypertamina untuk membeli Pertalite','Netral'),
(285,'Pemerintah Kota Bandung mengendarai sepeda motor menggunakan aplikasi Mypertamina untuk membeli Pertalite','Netral'),
(286,'membeli pertalite solar harus pakai mypertamina lihat daftar tempo Pemkot','Netral'),
(287,'bandung naik motor pakai aplikasi mypertamina','Netral'),
(288,'beli pertalite beli pertalite pakai mypertamina tahap sosialisasi Pemkot','Netral'),
(289,'bandung naik motor pakai aplikasi mypertamina beli pertalite','Netral'),
(290,'september turn java beli pertalite pakai mypertamina sindonews no t berita biasa','Positif'),
(291,'Besok saya akan membeli Pertalite diesel menggunakan','Netral'),
(292,'aplikasi Mypertamina. gaes, beli pertalite & solar pakai mypertamina gampang & praktis, lihat untungnya gampang banget pokoknya','Positif'),
(293,'pengguna motor tenang beli pertalite pakai mypertamina, naek','Positif'),
(294,'velg. Pengguna motor tenang membeli Pertalite menggunakan velg Mypertamina','Positif'),
(295,'beli gas kg pakai mypertamina interestnews beli BBM jenis pertalite beli gas kg pakai aplikasi mypertamina market director','Netral'),
(296,'jumat juli beli solar pertalite pakai aplikasi mypertamina mypertamina mypertamina','Netral'),
(297,'membeli pertalite menggunakan mypertamina sangat kritis, membaca berita sekarang mudah dan nyaman, unduh aplikasi ini untuk android ios, ini iscom, ini dotcom melalui','Positif'),
(298,'september beli pertalite pulau jawa harus menggunakan mypertamina','Netral'),
(299,'Pengemudi membeli Pertalite menggunakan aplikasi MyPertamina Bandung, Pertalite Motors , Pertamina, Mypertamina, SPBU, SPBU, Mobil, Regulasi Indonesia Nasional, PRMN, Pikiran, PRmnTeman,UMKM, Pikiran Rakyat,Median Kesalahpahaman jaringan','Netral'),
(300,'lihat jelas, beli pertalite pakai mypertamina, lengkap, cepat, berita ekonomi uang, indonesia ekonomi, ekonomi','Positif'),
(301,'beli minyak goreng pakai ktp peduli dan pelindung beli solar pertalite pakai aplikasi mypertamina sebentar pake sim','Netral'),
(302,'besok daerah uji coba beli solar pertalite pake','Netral'),
(303,'aplikasi mypertamina.   Pemerintah Kota Bandung mengendarai sepeda motor menggunakan aplikasi Mypertamina untuk membeli Pertalite','Netral'),
(304,'pengendara membeli pertalite menggunakan aplikasi mypertamina bandung','Netral'),
(305,'calon presiden beli migor & pertalite menggunakan aplikasi untuk melindungi pertamina saya silahkan masukan','Netral'),
(306,'register untuk membeli pertalite diesel menggunakan mypertamina','Netral'),
(307,'beli pertalite diesel menggunakan mypertamina secure data jamin','Positif'),
(308,'pertalite membeli lpg kilogram menggunakan aplikasi berita mypertamina fusilat','Netral'),
(309,'beli pertalite menggunakan mypertamina qr code untuk','Netral'),
(310,'cheat. heboh beli pertalite solar pakai mypertamina jelas pertalite mypertamina pertalite pertalite dan solar pertalite','Positif'),
(311,'alasan beli pertalite pakai mypertamina jabodetabek','Netral'),
(312,'beli pertalite solar pakai mypertamina besok warga jogja lokasi flash trial SPBU','Netral'),
(313,'karena putin set jual besok tarif listrik beli pertalite pakai mypertamina','Netral'),
(314,'beli pertalite solar pakai aplikasi mypertamina, subsidi BBM rp trilyun, enak seperti pengertian drun kadrun','Positif'),
(315,'fyi gt gt serentak september jawa beli pertalite pakai mypertamina serentak september jawa','Netral'),
(316,'juli beli pertalite solar bersubsidi pakai aplikasi pertalite saya prmn news','Netral'),
(317,'Pertalite diesel, Pertamina, masyarakat membeli melon gas menggunakan','Netral'),
(318,'aplikasi mypertamina. beli pertalite pakai aplikasi mypertamina, warganet, komentar pedas, ganggu masyarakat','Netral'),
(319,'pulau jawa beli pertalite pakai mypertamina serentak September','Netral'),
(320,'Pertalite solar beli lpg gas kg pakai mypertamina jual','Netral'),
(321,'pertalite beli elpiji kg pakai mypertamina','Netral'),
(322,'Pertamina beli pertalite pakai mypertamina seperti sopir pakai akun driver wkwkwk','Netral'),
(323,'beli pertalite menggunakan mypertamina daftar aplikasi untuk','Netral'),
(324,'website hp. beli pertalite bandung harus pakai aplikasi juli lihat buat akun mypertamina online','Netral'),
(325,'pertalite beli elpiji kg pakai mypertamina idcorner','Netral'),
(326,'aturan main besok tarif listrik beli pertalite pakai mypertamina terima kasih sad seat orang muka mata melotot muka mata melotot','Negatif'),
(327,'wajib pakai mypertamina beli pertalite solar pakai qr code','Netral'),
(328,'beli pertalite pakai aplikasi my pertamina, bayar pertamina saya pakai aplikasi linkaja, link top up, pakai aplikasi online banking, rekening bank, deposit uang, ribet, gampang, ribet, ribet','Negatif'),
(329,'motor harus pakai mypertamina beli pertalite','Netral'),
(330,'Polemik pembelian solar Pertalite pakai Mypertamina Kemal Palevi, bagaimana dengan SPBU untuk jemaah','Netral'),
(331,'Pengendara motor wajib beli Pertalite pakai Mypertamina','Netral'),
(332,'Pengguna motor pakai aplikasi mypertamina beli pertalite','Netral'),
(333,'Besok warga bandung beli pertalite solar pakai mypertamina cek','Netral'),
(334,'tipe kendaraan harus menggunakan mypertami na aplikasi beli pertalite solar dijual bulan juli','Netral'),
(335,'saya beli migor pakai id card, saya beli pertalite dengan mypertamina milu, saya pakai','Netral'),
(336,'kardus. Warga yang membeli Pertalite harus menggunakan aplikasi Mypertamina','Netral'),
(337,'daerah uji coba beli pertalite solar pakai mypertamina juli list tag Dieng Arafah bpjs ribka subang Kemenag Squidward sudah suka julia roberts iriana saudi arabia desi agnesmoboymagnet','Netral'),
(338,'Warga bandung wajib membeli Pertalite menggunakan','Netral'),
(339,'aplikasi MyPertamina motor. beli solar pertalite bersubsidi pakai mypertamina','Netral'),
(340,'beli pertalite solar pakai aplikasi mypertamina, warga dilarang pakai hp pom bensin','Netral'),
(341,'beli pertalite pakai mypertamina bersamaan september java','Netral'),
(342,'pertalite beli lpg kilogram menggunakan aplikasi mypertamina pt','Netral'),
(343,'beli pertalite pakai mypertamina sekaligus september jawa','Netral'),
(344,'beli pertalite pakai mypertamina serentak september java','Netral'),
(345,'Pertalite solar orang pakai mypertamina beli gas kilap kg meruntuhkan subsidi tahun ini harapan untuk gas kg ummat kelas sedang memikirkan mypertamina indihome','Negatif'),
(346,'tempat beli pertalite diesel pakai motor mypertamina daftar aplikasi','Netral'),
(347,'Syarat beli pertalite pakai mypertamina berlaku untuk','Netral'),
(348,'velg. Juli PT Pertamina mengajukan permohonan untuk mengatur pembelian solar pertalite menggunakan mypertamina dijual, mengatur pembelian solar pertalite menggunakan sepeda motor yang dijual mypertamina','Netral'),
(349,'isi bensin pertalite regis, beli gas lpg kg, daftar mypertamina negara maju, tinggal beli atau tidak pakai aplikasi indonesia','Positif'),
(350,'beli pertalite pakai mypertamina bersamaan september jawa','Netral'),
(351,'beli bahan bakar pertalite solar pom bensin pakai mypertamina lihat langkah-langkah registrasi','Netral'),
(352,'kendaraan, kriteria pembelian solar pertalite menggunakan','Netral'),
(353,'aplikasi mypertamina pertamina. thread juli beli pertalite solar area harus pakai aplikasi mypertamina pertamina','Netral'),
(354,'Beli minyak goreng pakai care di lindungi, beli pertalite pakai mypertamina yg gak punya hp gimana bisa gak serius belinya gampang repot','Positif'),
(355,'nya salah saya baru daftar, baru beli pertalite pake mypertamina qr varu, mobil tidak antri','Negatif'),
(356,'pertalite beli lpg kg pakai mypertamina','Netral'),
(357,'beli pertalite harus pakai mypertamina lihat daftar berkas pendaftaran','Netral'),
(358,'Warga khawatir beli pertalite susah pakai mypertamina Pertamina siap melangkah','Negatif'),
(359,'Pj Pjs sekretaris perusahaan pt pertamina patra niaga irto ginting uji coba polis beli pertalite pakai mypertamina tidak berhasil, anda naik motor test hanya pakai','Netral'),
(360,'velg. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting uji coba kebijakan untuk membeli pertalite menggunakan mypertamina tidak bekerja untuk sepeda motor uji coba hanya berlaku untuk','Netral'),
(361,'roda. Pjs PJS Corporate Secretary PT Pertamina Patra Niaga Irto Ginting Uji coba Kebijakan Pembelian Pertalite menggunakan MyPertamina tidak berlaku untuk sepeda motor. Uji coba hanya berlaku untuk','Netral'),
(362,'roda. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto uji coba kebijakan beli pertalite pakai mypertamina tidak berlaku untuk sepeda motor, uji coba berlaku untuk','Netral'),
(363,'velg. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting uji coba kebijakan membeli pertalite menggunakan mypertamina tidak bekerja untuk uji coba sepeda motor, hanya berlaku','Netral'),
(364,'roda. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting bijaksana percobaan membeli pertalite menggunakan mypertamina tidak bekerja untuk percobaan naik motor hanya menggunakan','Positif'),
(365,'roda. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting uji coba kebijakan untuk membeli pertalite menggunakan mypertamina tidak bekerja Anda naik sepeda motor uji coba hanya berlaku','Netral'),
(366,'roda. Pj PJS Corporate Secretary PT Pertamina Patra Niaga Irto Ginting Uji coba Kebijakan Pembelian Pertalite menggunakan MyPertamina tidak menjual untuk sepeda motor, Uji coba berlaku','Netral'),
(367,'roda. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting uji coba kebijakan untuk membeli pertalite menggunakan mypertamina jual untuk uji coba sepeda motor hanya berlaku untuk','Netral'),
(368,'roda. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting trial kebijakan membeli pertalite menggunakan mypertamina berlaku untuk uji coba sepeda motor hanya berlaku untuk','Netral'),
(369,'roda. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting bijaksana percobaan membeli pertalite menggunakan mypertamina tidak bekerja untuk sepeda motor percobaan hanya menggunakan','Positif'),
(370,'roda. Pj PJS Corporate Secretary PT Pertamina Patra Niaga Irto Ginting Uji coba kebijakan pembelian Pertalite menggunakan MyPertamina tidak berlaku untuk sepeda motor, uji coba berlaku untuk','Netral'),
(371,'roda. Pjs PJS Corporate Secretary PT Pertamina Patra Niaga Irto Ginting Uji coba Kebijakan Pembelian Pertalite menggunakan MyPertamina tidak berlaku untuk sepeda motor uji coba, hanya menggunakan','Netral'),
(372,'velg. bukan solusi beli gas kg pertalite pakai mypertamina beli migor curah pakai careprotect','Netral'),
(373,'Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting trial kebijakan beli pertalite pakai mypertamina dijual untuk trial sepeda motor hanya berlaku','Netral'),
(374,'velg. Pjs sekretaris perusahaan pt pertamina patra niaga irto ginting uji coba kebijakan membeli pertalite menggunakan mypertamina tidak berfungsi anda mengendarai sepeda motor uji coba hanya menggunakan','Netral'),
(375,'roda. Pjs PJS Corporate Secretary PT Pertamina Patra Niaga, Irto Ginting, uji coba bijak beli Pertalite pakai MyPertamina, Motor, Uji coba pakai','Positif'),
(376,'velg. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting trial bijaksana untuk membeli pertalite menggunakan mypertamina dijual untuk trial sepeda motor hanya','Positif'),
(377,'roda yang digunakan. Pjs PJS Corporate Secretary PT Pertamina Patra Niaga Irto Ginting Uji coba Kebijakan Pembelian Pertalite menggunakan MyPertamina TDX tidak berlaku untuk sepeda motor, uji coba berlaku untuk','Netral'),
(378,'roda. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting uji coba kebijakan untuk membeli pertalite menggunakan mypertamina tidak bekerja untuk uji coba sepeda motor hanya berlaku untuk','Netral'),
(379,'roda. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting trial policy beli pertalite pakai mypertamina tidak berlaku untuk motor trial, hanya','Netral'),
(380,'velg yang digunakan. Warga jogja di wilayah indonesia wajib lihat beli bbm pakai mypertamina pertalite solar baca portal lengkap yogoya mypertamina plt','Positif'),
(381,'pjs corporate secret pt pertamina patra niaga irto ginting percobaan bijak beli pertalite pakai mypertamina ga bisa','Positif'),
(382,'pertalite beli lpg kilogram harus pakai mypertamina','Netral'),
(383,'aktu pjs sekretaris perusahaan pt pertamina patra niaga irto ginting uji coba kebijakan beli pertalite menggunakan mypertamina tidak menjual sepeda motor, uji coba berlaku untuk','Netral'),
(384,'wheel drive. Pjs PJS Corporate Secretary PT Pertamina Patra Niaga Irto Ginting Uji coba Kebijakan Pembelian Pertalite menggunakan MyPertamina Tidak berlaku untuk sepeda motor uji coba, hanya berlaku untuk roda','Netral'),
(385,'Pjs Corporate Secretary PT pertamina patra niaga irto ginting uji coba kebijakan beli pertalite menggunakan mypertamina tidak kerja untuk sepeda motor uji coba hanya berlaku untuk','Netral'),
(386,'roda. Pj PJS Corporate Secretary PT Pertamina Patra Niaga Irto Ginting Uji coba kebijakan pembelian Pertalite menggunakan MyPertamina tidak berlaku untuk sepeda motor uji coba, hanya','Netral'),
(387,'velg yang digunakan. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting percobaan bijak membeli pertalite menggunakan mypertamina tidak berhasil untuk sepeda motor, percobaan menggunakan','Positif'),
(388,'velg. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting uji coba kebijakan untuk membeli pertalite menggunakan mypertamina tidak bekerja untuk uji coba sepeda motor hanya berlaku','Netral'),
(389,'roda. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting trial kebijakan membeli pertalite menggunakan mypertamina tidak berlaku untuk sepeda motor trial, hanya','Netral'),
(390,'velg yang diterapkan. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto uji coba kebijakan membeli pertalite menggunakan mypertamina tidak berhasil, Anda naik sepeda motor uji coba hanya berlaku','Netral'),
(391,'roda. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting uji coba kebijakan untuk membeli pertalite menggunakan','Netral'),
(392,'mypertamina Pjs sekretaris perusahaan pt pertamina patra niaga irto ginting percobaan bijaksana membeli pertalite menggunakan mypertamina tidak berlaku untuk sepeda motor uji coba hanya berlaku','Positif'),
(393,'wheel drive. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting uji coba kebijakan untuk membeli pertalite menggunakan mypertamina tidak bekerja untuk sepeda motor uji coba hanya berlaku untuk','Netral'),
(394,'roda. Pjs PJS Corporate Secretary PT Pertamina Patra Niaga Irto Ginting Uji coba Kebijakan Pembelian Pertalite menggunakan MyPertamina tidak berlaku untuk sepeda motor. Uji coba hanya berlaku untuk','Netral'),
(395,'kendaraan beroda. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto uji coba kebijakan membeli pertalite menggunakan mypertamina tidak berlaku untuk sepeda motor, uji coba berlaku untuk','Netral'),
(396,'wheel drive. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto memulai uji coba kebijakan membeli pertalite menggunakan mypertamina tidak berlaku untuk uji coba wahana sepeda motor, hanya berlaku','Netral'),
(397,'roda. Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting bijaksana percobaan membeli pertalite menggunakan mypertamina tidak bekerja untuk percobaan naik sepeda motor hanya berlaku','Positif'),
(398,'roda. Ayo pak Jokowi bantu presiden, rakyat sudah pusing karena sudah diatur beli solar pertalite pakai aplikasi pertamina saya, beli migor, pakai rawat, lindungi, beli gas, kg juga pakai pertamina saya, Pusing','Netral'),
(399,'Pjs sekretariat korporat pt pertamina patra niaga irto ginting uji coba kebijakan membeli pertalite menggunakan mypertamina tidak berhasil, Anda naik sepeda motor uji coba hanya berlaku','Netral'),
(400,'roda. Pjs Sekretaris Perusahaan pt pertamina patra niaga irto ginting trial kebijakan beli pertalite pakai mypertamina bukan jual motor, trial pakai velg','Netral'),
(401,'Pjs Sekretaris Perusahaan pt pertamina patra niaga irto memulai uji coba kebijakan pembelian pertalite menggunakan mypertamina yang dijual untuk sepeda motor uji coba hanya berlaku untuk','Netral'),
(402,'kendaraan beroda.   ','Positif'),
(403,'wheel drive.   ','Netral'),
(404,'warga bandung menolak untuk membeli pertalite menggunakan','Netral'),
(405,'aplikasi mypertamina.   ','Netral'),
(406,'Pertalite solar, Pertamina, orang beli gas melon pake','Netral'),
(407,'aplikasi mypertamina.   ','Negatif'),
(408,'saya bingung, keadaan Wakanda Mall peduli lindungi kapal pakai Ferzizi, beli Pertalite pakai Mypertamina Linkaja, Negara, Mo jual aplikasi','Negatif'),
(409,'Hoaks Solo Night Trial Beli Pertalite Diesel Pakai MyPertamina','Netral'),
(410,'beli pertalite solar pakai mypertamina data aman garansi','Positif'),
(411,'pertalite beli lpg kilogram harus pakai mypertamina','Netral'),
(412,'kendaraan beli pertalite solar pakai mypertamina sudah clear, lengkap lihat mypertamina','Positif'),
(413,'setelah itu pertalite beli lpg bersubsidi pakai mypertamina','Netral'),
(414,'mypertamina','Netral'),
(415,'aplikasi   Bajingan, Anda tidak tahu apa artinya Pertamina membeli Pertalite menggunakan aplikasi. Jangan menyalin. Pertamina suruh pakai MyPertamina untuk beli Pertalite BBM bersubsidi agar mafia tidak main-main jatah','Netral'),
(416,'pertalite solar beli lpg kg pakai','Netral'),
(417,'aplikasi my pertamina. Saya tidak mengerti siapa yang membeli Pertalite menggunakan Pertamina saya, isi bio, ID, ID, dll. Jika Anda membawa kendaraan, namanya tidak membeli Pertalite, jadi bagaimana jika saya membeli Pertalite menggunakan kendaraan, Orang tua saya tidak mengerti sumpah bodoh sekali menyerap info macam ni muka tanpa mulut','Negatif'),
(418,'beli solar pertalite pakai','Netral'),
(419,'aplikasi mypertamina.   Pertalite diesel membeli melon gas menggunakan','Netral'),
(420,'aplikasi mypertamina.   Daerah Beritasonora wajib pakai mypertamina beli pertalite solar Juli','Netral'),
(421,'newsjabar juli beli pertalite solar lokal wajib pakai mypertamina belisolar pakai aplikasi buypertalite pakai aplikasi mypertamina apilasi','Netral'),
(422,'warga jogja, nikmati trial beli pertalite pakai aplikasi mypertamina, tahap speechless, atur wajah letih','Positif'),
(423,'sukabumi Sopir angkot kota yang beli pertalite wajib pakai mypertamina','Netral'),
(424,'beli pertalite pakai aplikasi mypertamina, link only, transaksi, jangan pake linkaja, pakai mypertamina, kalo ga ribet ini beneran indonesia, sik','Positif'),
(425,'pertalite beli lpg kilogram pake','Netral'),
(426,'aplikasi mypertamina.   Sopir angkot ribet banget beli pertalite solar pakai mypertamina','Negatif'),
(427,'Sopir angkot ribet banget beli pertalite solar pakai mypertamina Sopir','Negatif'),
(428,'angkot susah beli pertalite solar pakai mypertamina','Negatif'),
(429,'Di depan Karni Ilyas Arya Sinulingga jelas beli pertalite harus pakai mypertamina aryasinulingga karniilyas pertalite mypertamina','Positif'),
(430,'implementasi peraturan pembelian pertalite solar menggunakan mypertamina, mengemudi sepeda motor, mengendarai mobil dengan roda sarap','Netral'),
(431,'Pjs pjs sekretaris perusahaan pt pertamina patra niaga irto ginting percobaan bijak membeli pertalite menggunakan mypertamina jual motor tempobusiness','Positif'),
(432,'beli pertalite solar pakai mypertamina sopir angkot pakai android','Netral'),
(433,'beli pertalite solar pakai mypertamina besok warga jogja lokasi test station baru flash','Positif'),
(434,'Orang hidup dengan batasan canggih dalam teknologi aplikasi beli Migor pakai Duli Protect beli Pertalite pakai My Pertamina protes menyindir bahwa power sudah kena pasal hinaan masyarakat','Negatif'),
(435,'sabra pertalite solar,pertamina,orang beli melon gas pakai','Netral'),
(436,'aplikasi mypertamina.   juli beli pertalite solar harus pakai','Netral'),
(437,'aplikasi mypertamina.   daftar tempat beli solar amp pertalite pakai mypertamina','Netral'),
(438,'beli minyak curah, pakai hati-hati dan lindungi beli pertalite pakai mypertamina','Netral'),
(439,'pks kritik beli pertalite pakai mypertamina dianggap repot konsumen temponasional','Netral'),
(440,'salah logika beli pertalite pakai mypertamina mypertamina pakai hp HP tidak gas stasiun salah logika beli pertalite pakai mypertamina mypertamina pakai hp bukan beli hp bukan beli pertalite','Negatif'),
(441,'Pertalite solar, Pertamina, orang beli gas melon pake','Netral'),
(442,'aplikasi mypertamina.   Rezim biadab menyiksa rakyat di Pertalite Diesel Pertamina, masyarakat membeli gas melon menggunakan','Netral'),
(443,'aplikasi MyPertamina.   beli pertalite & solar pakai mypertamina gampang & praktis, lihat untungnya gampang banget, yuk download guys','Positif'),
(444,'Harusnya masyarakat menolak Pertamina bertindak atas dasar hukum perintah untuk menetapkan kriteria penerimaan Pertalite, warga bandung tolak beli Pertalite pakaiMypertamina','Positif'),
(445,'Seharusnya masyarakat menolak Pertamina untuk bertindak atas dasar hukum perintah penetapan kriteria penerimaan Pertalite, warga Bandung menolak membeli Pertalite menggunakan','Positif'),
(446,'aplikasi Mypertamina.   main hp ban SPBU, beli pertalite pakai aplikasi mypertamina, kalau bodo guling-guling di lantai ketawa guling-guling di lantai ketawa guling-guling di lantai ketawa','Negatif'),
(447,'Bikin repot sopir angkot kota sukabumi komplain beli Pertalite pakai Mypertamina','Netral'),
(448,'Ayo monggo, beli pertalite & solar pakai mypertamina, mudah & praktis, lihat manfaat dasarnya, simple banget','Positif'),
(449,'Pertamina bijak beli Pertalite pakai MyPertamina Tempobusiness limit','Positif'),
(450,'pertalite beli lpg kg pakai mypertamina','Netral'),
(451,'juli beli BBM bersubsidi harus pakai mypertamina beli pertalite biodiesel pakai linkaja','Netral'),
(452,'juli beli BBM bersubsidi harus pakai mypertamina beli pertalite biodiesel pakai linkaja','Netral'),
(453,'uji coba beli pertalite pakai mypertamina juli','Netral'),
(454,'trial beli pertalite pakai mypertamina tanggal juli tempofoto','Netral'),
(455,'TKI beli pakai aplikasi lindungi dan lindungi, beli Pertalite Mai harus pakai Mypertamina, Pertalite adalah siap membatasi misi utama amanat rakyat t o urus rakyat dan urusi konflik negara','Positif'),
(456,'SPBU sumatera uji coba beli pertalite pakai mypertamina','Netral'),
(457,'untuk info ya gaes, beli pertalite & solar pakai mypertamina gampang & praktis, lihat keuntungan download','Positif'),
(458,'beli pertalite & solar pakai mypertamina gampang & praktis lihat untung gampang banget nyarinya, acungan jempol nya','Positif'),
(459,'guys, beli pertalite & solar pakai mypertamina gampang & praktis, lihat untungnya gampang banget, cuma','Positif'),
(460,'saya beli pertalite & solar pakai mypertamina jadi gampang & praktis, lihat ini untungnya guys, winking face','Positif'),
(461,'Ayo guys beli pertalite & solar pakai mypertamina, mudah & praktis, lihat manfaat dasarnya, simple','Positif'),
(462,'banget Beli pertalite & solar pakai mypertamina gampang & praktis. Nih bagusnya pakai mypertamina thumbs up light skin tone thumbs up light skin tone','Positif'),
(463,'beli pertalite & solar pakai mypertamina gampang & praktis lihat untungnya gampang','Positif'),
(464,'guys, beli pertalite & solar pakai mypertamina gampang & praktis, lihat untungnya ok hand ok hand','Positif'),
(465,'Beli pertalite & solar pakai mypertamina gampang & praktis, lihat untungnya di bawah ini guys','Positif'),
(466,'beli pertalite & solar pakai mypertamina gampang & praktis, lihat untungnya sungguh gampang yuk download guys','Positif'),
(467,'Banyak negara yang mengatur, mengatur, beli migorcur pake aplikasi pel nik, beli pertalite diesel, daftar mypertamina Thinking face','Positif'),
(468,'pertalite beli elpiji bersubsidi pake mypertamina bayangin aja','Netral'),
(469,'beli minyak goreng pake careprotect beli pertalite pake mypertamina mundur aja gan jangan kalian','Netral'),
(470,'juli beli BBM bersubsidi harus pakai mypertamina beli biodiesel pertalite pakai linkaja','Netral'),
(471,'pertamina harus beli pertalite pakai prin barcode mypertamina susah, ayo, susah zany face zany face','Negatif'),
(472,'beli pertalite & solar pakai mypertamina gampang & praktis, lihat untungnya gampang banget, ayo download guys','Positif'),
(473,'main pom bensin dilarang, harus pakai aplikasi mypertamina untuk beli pertalite','Netral'),
(474,'Pertalite diesel, Pertamina, masyarakat beli gas melon menggunakan','Netral'),
(475,'aplikasi mypertamina.   Gerard menginformasikan kalau beli Pertalite pakai Mypertamina Raphinha','Positif'),
(476,'guys, beli pertalite & solar pakai mypertamina gampang & praktis, lihat untungnya, ok hand ok','Positif'),
(477,'beli pertalite & solar pakai mypertamina gampang & praktis, lihat untungnya kan gampang banget, thumbs up light skin tone thumbs up light skin tone','Positif'),
(478,'Area wajib beli Pertalite Biosolar pakai Mypertamina Jabodetabek','Netral'),
(479,'Saya beli pertalite & diesel pakai mypertamina jadi gampang & praktis, check this out, untungnya guys, winking face','Positif'),
(480,'beli pertalite & diesel pakai mypertamina ini mudah & praktis lihat untungnya gampang banget di acungi jempol buat','Positif'),
(481,'info nya gaes beli pertalite & solar pakai mypertamina gampang & praktis lihat untung rugi download','Positif'),
(482,'pertalite beli gas elpiji kg pakai mypertamina lengkap klik link jakarta belielpiji gas elpiji mypertamina','Positif'),
(483,'Kak, saya beli Pertalite, saya beli Pertamax, saya tidak pakai Mypertamina','Netral'),
(484,'mypertamina','Netral'),
(485,'aplikasilikasi.   beli pertalite & solar pakai mypertamina gampang & praktis lihat keuntungannya gampang banget acungan jempol','Positif'),
(486,'Fyi gaes, beli pertalite & solar pakai mypertamina gampang & praktis cek mudah untung Pertamina keren','Positif'),
(487,'infonya gaes, beli pertalite & solar pakai mypertamina gampang & praktis, lihat untungnya download','Positif'),
(488,'beli pertalite & solar pakai mypertamina gampang & praktis, lihat untungnya gampang banget, acungan jempolnya','Positif'),
(489,'saya beli pertalite & solar pakai mypertamina jadi ini mudah & praktis, simak ini untungnya guys, winking face','Positif'),
(490,'saya beli pertalite & diesel pakai mypertamina jadi gampang & praktis, check this this, untungnya guys, winking face','Positif'),
(491,'for your info guys, beli pertalite & diesel pakai mypertamina gampang & praktis lihat untung download','Positif'),
(492,'beli pertalite & solar pakai mypertamina mudah & praktis lihat untungnya gampang banget acungan jempol','Positif'),
(493,'beli pertalite & solar pakai mypertamina mudah & praktis lihat untungnya r gampang banget, acungan jempol tona kulit cerah acungan jempol','Positif'),
(494,'daerah tona kulit cerah harus pakai mypertamina beli pertalite solar bersubsidi mypertamina fuel pertalite','Netral'),
(495,'guys, beli pertalite & solar pakai mypertamina gampang & praktis, lihat untungnya, ok tangan ok','Positif'),
(496,'hasil , bapak ibu beli minyak goreng pakai nik dan beli pertalite pakai pertamina saya','Netral'),
(497,'beli pertalite & solar pakai pom bensin mypertamina jogja repot','Netral'),
(498,'beli pertalite & solar pakai mypertamina gampang & praktis, lihat untungnya gampang banget, yuk download guys ok','Positif'),
(499,'belipertalite solar bersubsidi pakai aplikasi pertamina saya beli minyak goreng dengan aplikasi care protect beli lpg kg juga pakai aplikasi pertamina saya marah indeks backhand menunjuk ke bawah indeks backhand menunjuk ke bawah wajah menyeringai dengan mata tersenyum','Negatif'),
(500,'beli pertalite solar harus pakai mypertamina ylki option','Netral');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
